services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: company
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "5123:8080"
    volumes:
      - ./src/main/resources/templates:/usr/app/src/main/resources/templates
    depends_on:
      - postgres